### ISSUE TITLE
FUNCTION OF BUCKET ITERATOR

### ISSUE THREAD

**Issue by RVT123123** [First-Of-His-Name/speech-emotion-recognition#8]
I want to know what is the main function of bucket iterator and what are parameters and return value.

**Comment by amanbasu** [comment]
In this project, we have used human speech signals for detecting the emotions. Now since these voice samples can vary in time, we need to convert them to a common shape that requires padding (neural networks require data in a fixed shape for training).
Either whole data can be padded altogether or batch-wise, the later one is more memory efficient and we have used Bucket Iterator for the same.
Bucket Iterator takes the batch size as the parameter and returns a random padded batch of data including both input and its corresponding label.

**Comment by Jon-Zbw** [comment]
I want to know what is the main function of 'Mel.py'  ,  Just want to show the difference between FBANK and MFCC?

**Comment by amanbasu** [comment]
Yes, it is just for reference and understanding Mel.

**Comment by Jon-Zbw** [comment]
when i copy your ‘class BucketedDataIterator（）：’ 
 I don't know where the problem is. Can you help me?
Traceback (most recent call last):
  File "D:/Project/pycharm/RNN/create_mfcc.py", line 164, in <module>
    mini_batch = tr.next_batch(128)
  File "D:/Project/pycharm/RNN/create_mfcc.py", line 160, in next_batch
    x_i[:res['lengths'].values[i]] = res['MFCC'].values[i]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by Jon-Zbw** [comment]
my file like this：
........................................................... MFCC  ........................................... lengths
0  [[-10.494777560823318, 19.205118287686812, 16....  ...  1099.0
1  [[-11.632857909892738, 5.8760442872698695, 29....  ...  1099.0
2  [[-8.773702814090234, -12.86215112148708, -7.2...  ...   299.0
3  [[-8.411895008114222, -1.9307392294278005, -7....  ...   299.0
4  [[-6.969186995608002, -17.02179303376442, -23....  ...   299.0
